/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sorryisme' at '18. 3. 17 오후 11:16' with Gradle 2.10
 *
 * @author sorryisme, @date 18. 3. 17 오후 11:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
